exports.ErrorCode = {
  EMAIL_ERROR: 1,
  PASSWORD_ERROR: 2,
  FIRST_NAME_ERROR: 3,
  LAST_NAME_ERROR: 4,
  FUNCTION_ERROR: 5,
  COMPANY_NAME_ERROR: 6,
  PHONE_NUMBER_ERROR: 7,
  WEBSITE_ERROR: 8,
  INDUSTRY_ERROR: 9,
  COUNTRY_ERROR: 10,
  CITY_ERROR: 11,
  POSTAL_ERROR: 12,
  STREETADDRESS_ERROR: 13,

  // Add more error codes as needed
};
